#!/bin/bash

# script/publish
# Publish the extension to the marketplace

set -eu

cd "$(dirname "$0")/.."

# Install the required tools
./script/bootstrap

# Publish extension
VERSION=$(grep version package.json | sed 's|.*"version": "\(.*\)",.*|\1|')

read -p "You are about to release v.${VERSION} of the extension. Proceed? [Y/n] " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
	vsce publish
fi

